### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '10.0'

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/fedora-distro-aliases#17]
```
$ tito release --no-build all
Creating output directory: /tmp/tito
Will release to the following targets: all
Releasing to target: all
Checking for tag [fedora-license-data-1.53-1] in git repo [git@gitlab.com:fedora/legal/fedora-license-data.git]
Working in: /tmp/tito/release-fedora-license-dataq6dyx5wx
Traceback (most recent call last):
  File "/usr/bin/tito", line 33, in <module>
    sys.exit(load_entry_point('tito==0.6.26', 'console_scripts', 'tito')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tito/cli.py", line 944, in main
    CLI().main(sys.argv[1:])
  File "/usr/lib/python3.12/site-packages/tito/cli.py", line 210, in main
    return module.main(argv)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tito/cli.py", line 635, in main
    releaser = releaser_class(
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tito/release/distgit.py", line 66, in __init__
    self.git_branches = self._branches()
                        ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tito/release/distgit.py", line 111, in _branches
    aliases = get_distro_aliases()
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/fedora_distro_aliases/__init__.py", line 36, in get_distro_aliases
    distros.sort(key=lambda x: int(x.version_number))
  File "/usr/lib/python3.12/site-packages/fedora_distro_aliases/__init__.py", line 36, in <lambda>
    distros.sort(key=lambda x: int(x.version_number))
                               ^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10.0'
```

**Comment by FrostyX** [comment]
I couldn't reproduce with `tito release --no-build all`:

```
ERROR: No such releaser configured: all
```

But it can be simply reproduced with:

```
from fedora_distro_aliases import get_distro_aliases
get_distro_aliases()
```

Anyway, PR #18 fixes the issue, thank you :-)
